"use client";
import { CopyButton } from "@/components/copy-button";
import { aerialVehicleFields } from "@/lib/schedule-fields";
import type { PreviousSchedule, ScheduleSubmitInput } from "@/lib/types";
type Equipment = Pick<ScheduleSubmitInput, "aerialWorkVehicles" | "usesFire" | "fireArea" | "usesTachiuma" | "tachiumaNotes" | "workArea">;
export function ScheduleEquipmentFields({ form, previous, onChange }: { form: Equipment; previous?: PreviousSchedule | null; onChange: (fields: Partial<ScheduleSubmitInput>) => void }) {
  const aerial = form.aerialWorkVehicles?.[0]?.workArea ?? "";
  const previousAerial = previous?.aerialWorkVehicles?.[0]?.workArea || previous?.aerialWorkVehicleFloor || "";
  const usesAerial = Boolean(form.aerialWorkVehicles?.length);
  return <div className="space-y-2">
    <div className="rounded-md border border-sky-300 bg-sky-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-sky-950"><input type="checkbox" className="h-5 w-5" checked={usesAerial} onChange={(e) => onChange(aerialVehicleFields(e.target.checked ? [{ workArea: "", vehicleCount: 1 }] : []))} />高所作業車</label>{usesAerial && <div className="mt-2 border-t border-sky-200 pt-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><span className="label">使用場所と台数を入力。<span className="required-mark">必須</span></span><CopyButton label="高所作業車を前回と同じにする" disabled={!previousAerial} onCopy={() => onChange(aerialVehicleFields([{ workArea: previousAerial, vehicleCount: 1 }]))} /></div><textarea aria-label="高所作業車の使用場所と台数" className="textarea" required maxLength={500} value={aerial} placeholder={"例：B2F 3台、2F 3台\n高車についての連絡事項はこちらに入力。"} onChange={(e) => onChange(aerialVehicleFields([{ workArea: e.target.value, vehicleCount: 1 }]))} /></div>}</div>
    <div className="rounded-md border border-emerald-300 bg-emerald-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-emerald-950"><input type="checkbox" className="h-5 w-5" checked={form.usesTachiuma} onChange={(e) => onChange({ usesTachiuma: e.target.checked, tachiumaNotes: e.target.checked ? form.tachiumaNotes : "" })} />立ち馬</label>{form.usesTachiuma && <div className="mt-2 border-t border-emerald-200 pt-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><span className="label">使用場所と台数を入力。<span className="required-mark">必須</span></span><CopyButton label="立ち馬を前回と同じにする" disabled={!previous?.tachiumaNotes} onCopy={() => onChange({ tachiumaNotes: previous?.tachiumaNotes ?? "" })} /></div><textarea aria-label="立ち馬の使用場所と台数" className="textarea" required maxLength={500} value={form.tachiumaNotes} placeholder={"例：B2F 3台、2F 3台\n立ち馬についての連絡事項はこちらに入力。"} onChange={(e) => onChange({ tachiumaNotes: e.target.value })} /></div>}</div>
    <div className="rounded-md border border-rose-300 bg-rose-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-rose-950"><input type="checkbox" className="h-5 w-5" checked={form.usesFire} onChange={(e) => onChange({ usesFire: e.target.checked, fireArea: e.target.checked ? form.fireArea : "" })} />火気使用</label>{form.usesFire && <div className="mt-2 border-t border-rose-200 pt-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><label className="label" htmlFor="fire-area">使用エリアを入力してください。<span className="required-mark">必須</span></label><button type="button" className="btn btn-secondary min-h-10 py-1.5 text-sm" onClick={() => onChange({ fireArea: form.workArea })}>作業エリアと同じ</button></div><input id="fire-area" className="input" required maxLength={200} value={form.fireArea} placeholder="例：B2F" onChange={(e) => onChange({ fireArea: e.target.value })} /></div>}</div>
  </div>;
}
