"use client";
import { CopyButton } from "@/components/copy-button";
import { aerialVehicleFields, parseTachiumaValue } from "@/lib/schedule-fields";
import type { PreviousSchedule, ScheduleSubmitInput } from "@/lib/types";
type Equipment = Pick<ScheduleSubmitInput, "aerialWorkVehicles" | "usesFire" | "fireArea" | "usesTachiuma" | "tachiumaNotes" | "tachiumaCount" | "workArea">;
export function ScheduleEquipmentFields({ form, previous, onChange }: { form: Equipment; previous?: PreviousSchedule | null; onChange: (fields: Partial<ScheduleSubmitInput>) => void }) {
  const aerial = form.aerialWorkVehicles?.[0] ?? { workArea: "", vehicleCount: 1 };
  const previousAerial = previous?.aerialWorkVehicles?.[0]?.workArea || previous?.aerialWorkVehicleFloor || "";
  const previousTachiuma = parseTachiumaValue(previous?.tachiumaNotes);
  const usesAerial = Boolean(form.aerialWorkVehicles?.length);
  return <div className="space-y-2">
    <div className="rounded-md border border-sky-300 bg-sky-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-sky-950"><input type="checkbox" className="h-5 w-5" checked={usesAerial} onChange={(e) => onChange(aerialVehicleFields(e.target.checked ? [{ workArea: "", vehicleCount: 1 }] : []))} />高所作業車</label>{usesAerial && <div className="mt-2 border-t border-sky-200 pt-2"><div className="flex items-end gap-2"><label className="field min-w-0 flex-1"><span className="label">使用内容<span className="required-mark">必須</span></span><input className="input" required maxLength={500} value={aerial.workArea} placeholder="例：B2Fで2台、2Fで2台" onChange={(e) => onChange(aerialVehicleFields([{ ...aerial, workArea: e.target.value }]))} /></label><CopyButton label="高所作業車を前回と同じにする" disabled={!previousAerial} onCopy={() => onChange(aerialVehicleFields([{ workArea: previousAerial, vehicleCount: previous?.aerialWorkVehicles?.[0]?.vehicleCount ?? previous?.aerialWorkVehicleCount ?? 1 }]))} /></div></div>}</div>
    <div className="rounded-md border border-emerald-300 bg-emerald-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-emerald-950"><input type="checkbox" className="h-5 w-5" checked={form.usesTachiuma} onChange={(e) => onChange({ usesTachiuma: e.target.checked, tachiumaNotes: e.target.checked ? form.tachiumaNotes : "", tachiumaCount: null })} />立ち馬</label>{form.usesTachiuma && <div className="mt-2 border-t border-emerald-200 pt-2"><div className="flex items-end gap-2"><label className="field min-w-0 flex-1"><span className="label">連絡事項（任意）</span><input className="input" maxLength={500} value={form.tachiumaNotes} placeholder="例：2F、3Fで3台使用。" onChange={(e) => onChange({ tachiumaNotes: e.target.value })} /></label><CopyButton label="立ち馬を前回と同じにする" disabled={!previous?.tachiumaNotes} onCopy={() => onChange({ tachiumaNotes: previousTachiuma.area, tachiumaCount: null })} /></div></div>}</div>
    <div className="rounded-md border border-rose-300 bg-rose-50/60 p-2"><label className="flex min-h-8 cursor-pointer items-center gap-2 font-bold text-rose-950"><input type="checkbox" className="h-5 w-5" checked={form.usesFire} onChange={(e) => onChange({ usesFire: e.target.checked, fireArea: e.target.checked ? form.fireArea : "" })} />火気使用</label>{form.usesFire && <div className="mt-2 border-t border-rose-200 pt-2"><div className="flex items-end gap-2"><label className="field min-w-0 flex-1"><span className="label">連絡事項（任意）</span><input className="input" maxLength={200} value={form.fireArea} placeholder="例：2F、3Fで使用。" onChange={(e) => onChange({ fireArea: e.target.value })} /></label><button type="button" className="btn btn-secondary min-h-10 shrink-0 py-1.5 text-sm" onClick={() => onChange({ fireArea: form.workArea })}>作業エリアと同じ</button></div></div>}</div>
  </div>;
}
