"use client";
import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { apiFetch } from "@/lib/api-client";
import type { EquipmentFloorRow } from "@/lib/types";
export function EquipmentFloorsPanel() {
  const [floors, setFloors] = useState<EquipmentFloorRow[]>([]); const [name, setName] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [editName, setEditName] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async () => { const response = await apiFetch("/api/admin/equipment-floors"); const body = await response.json(); if (!response.ok) throw new Error(body.error); setFloors(body.floors ?? []); };
  useEffect(() => { void refresh().catch(() => setMessage("フロア一覧を取得できませんでした。")); }, []);
  const mutate = async (method: string, body?: object, query = "") => { setBusy(true); setMessage(""); try { const response = await apiFetch(`/api/admin/equipment-floors${query}`, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setName(""); setEditing(null); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "更新できませんでした。"); } finally { setBusy(false); } };
  return <section className="panel mt-3 grid gap-3 p-4"><div><h2 className="text-lg font-bold">設備フロア管理</h2><p className="text-sm text-slate-600">高所作業車・立ち馬の入力候補を管理します。</p></div>{message && <p className="notice-error text-sm">{message}</p>}<div className="flex gap-2"><input className="input" value={name} maxLength={30} placeholder="例：4F" onChange={e => setName(e.target.value)}/><button type="button" className="btn btn-primary" disabled={busy || !name.trim()} onClick={() => void mutate("POST", { name })}><Plus size={16}/>追加</button></div><div className="grid gap-2">{floors.map(floor => <div key={floor.id} className="flex items-center gap-2 rounded-md bg-slate-50 p-2">{editing === floor.id ? <input className="input" value={editName} onChange={e => setEditName(e.target.value)}/> : <span className="min-w-0 flex-1 font-semibold">{floor.name}</span>}<div className="ml-auto flex gap-2">{editing === floor.id ? <><button className="btn btn-primary" type="button" disabled={busy} onClick={() => void mutate("PATCH", { id: floor.id, name: editName })}>保存</button><button className="btn btn-secondary" type="button" onClick={() => setEditing(null)}>取消</button></> : <><button className="btn btn-secondary h-9 w-9 p-0" type="button" onClick={() => { setEditing(floor.id); setEditName(floor.name); }} aria-label={`${floor.name}を編集`}><Pencil size={16}/></button><button className="btn btn-secondary h-9 w-9 p-0 text-red-700" type="button" disabled={busy} onClick={() => void mutate("DELETE", undefined, `?id=${encodeURIComponent(floor.id)}`)} aria-label={`${floor.name}を削除`}><Trash2 size={16}/></button></>}</div></div>)}</div></section>;
}
